name: SociaLyze Desktop Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  contents: write

env:
  PROJECT_DIR: socialyze   # <— set to your Flutter subfolder name

jobs:
  build-desktop:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            build: windows
            zip: SociaLyze_Windows.zip
            out_path: build/windows/x64/runner/Release
          - os: macos-latest
            build: macos
            zip: SociaLyze_macOS.zip
            out_path: build/macos/Build/Products/Release
          - os: ubuntu-latest
            build: linux
            zip: SociaLyze_Linux.zip
            out_path: build/linux/x64/release/bundle
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Show workspace
        run: |
          pwd
          ls -la
          echo "Project dir listing:"
          ls -la "${{ env.PROJECT_DIR }}"

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install Linux deps
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev

      - name: flutter pub get
        working-directory: ${{ env.PROJECT_DIR }}
        run: flutter pub get

      - name: enable desktop
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          case "${{ matrix.build }}" in
            windows) flutter config --enable-windows-desktop ;;
            macos)   flutter config --enable-macos-desktop ;;
            linux)   flutter config --enable-linux-desktop ;;
          esac

      - name: build
        working-directory: ${{ env.PROJECT_DIR }}
        run: flutter build ${{ matrix.build }} --release

      - name: zip (Windows)
        if: matrix.os == 'windows-latest'
        working-directory: ${{ env.PROJECT_DIR }}
        shell: pwsh
        run: Compress-Archive -Path "${{ matrix.out_path }}\*" -DestinationPath "${{ matrix.zip }}"

      - name: zip (macOS)
        if: matrix.os == 'macos-latest'
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          cd "${{ matrix.out_path }}"
          # If your bundle name differs, replace 'SociaLyze.app'
          zip -r "../../${{ matrix.zip }}" "SociaLyze.app"

      - name: zip (Linux)
        if: matrix.os == 'ubuntu-latest'
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          cd "${{ matrix.out_path }}/.."
          zip -r "../../${{ matrix.zip }}" "bundle"

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.zip }}
          path: ${{ env.PROJECT_DIR }}/${{ matrix.zip }}

      - name: attach to release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.PROJECT_DIR }}/${{ matrix.zip }}
